// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: GitHub
---
*/
package endpoints

import (
	"context"

	"github.com/365admin/koksmat-release/execution"
	"github.com/swaggest/usecase"
)

func ReleaseGithubPost() usecase.Interactor {
	type Request struct {
		Kitchenname string `query:"kitchenname" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "koksmat-release", "release", "10-release.ps1", "", "-kitchenname", input.Kitchenname)
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("GitHub")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Release")
	return u
}
